/** This file is autogenerated - Edit the source clock tree instead! */
#ifdef TARGET_CLOCK_H
#error "Target clock file should ONLY be included from ClkMgr implementation!"
#define TARGET_CLOCK_H
#endif

#define C_NULL              0x0000
#define C_AUXHFRCO          0xb9a9
#define C_DBG               0x4741
#define C_MSC               0xd69c
#define C_HFXO              0x658c
#define C_HFRCO             0x5300
#define C_LFXO              0x558d
#define C_LFRCO             0x93f1
#define C_ULFRCO            0x8dd9
#define C_HF_SEL            0x3c57
#define C_HFPER             0x3a62
#define C_HFPER_DIV         0x1ada
#define C_HFCORE_DIV        0x6936
#define C_LFA_SEL           0x0d75
#define C_LFA_RTC_DIV       0xe029
#define C_LFA_LETIMER0_DIV  0x78ec
#define C_LFA_LCD_DIV       0x0661
#define C_LFA_FRAME_DIV     0xa36f
#define C_PCNT_EN           0x7ebf
#define C_LFB_SEL           0x0d31
#define C_LEUART_0_DIV      0xe72c
#define C_LEUART_1_DIV      0x2711
#define C_USART_0           0xb562
#define C_USART_1           0x75a3
#define C_USART_2           0x74e3
#define C_UART_0            0xcd7c
#define C_TMR_0             0xc5be
#define C_TMR_1             0x057f
#define C_TMR_2             0x043f
#define C_ACMP_0            0x0c40
#define C_ACMP_1            0xcc81
#define C_PRS               0x8c0c
#define C_DAC_0             0x532c
#define C_GPIO              0xe562
#define C_VCMP              0x14d5
#define C_ADC_0             0x9fe0
#define C_I2C_0             0x161b
#define C_AES               0x7953
#define C_DMA               0xb5c4
#define C_EBI               0x4391
#define C_LE                0x83f4
#define C_HFCORE_DIV2       0xc368
#define C_RTC               0x20af
#define C_LETIMER_0         0xc734
#define C_LCD               0x1481
#define C_PCNT              0xafd4
#define C_LEUART_0          0x7c2c
#define C_LEUART_1          0xbced
#define C_WDOG_SEL          0x856b
